# deploy docs to gh-pages branch
name: typedoc

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  deploy-docs-to-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Retrieve the cached "node_modules" directory (if present)
        uses: actions/cache@v4
        id: node-cache
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies (if the cached directory was not found)
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build the project
        run: npm run build

      - name: Create the docs directory
        run: npm run docs

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs
